# Generated by Django 5.0.12 on 2025-05-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='subcategory_id',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='category_id',
        ),
    ]
