# Generated by Django 5.0.12 on 2025-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp1', '0002_rename_subcategory_product_subcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
