# Generated by Django 5.0.12 on 2025-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp1', '0003_product_price_product_quantity_product_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
