# Generated by Django 5.0.12 on 2025-05-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp1', '0004_login_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp1.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp1.product')),
            ],
        ),
    ]
